spring.application.name=Schedular-App

spring.datasource.url=jdbc:postgresql://localhost:5432/scheduler
spring.datasource.username= postgres
spring.datasource.password= admin
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.resources.add-mappings=false

spring.datasource.initialize=true
spring.datasource.continue-on-error=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true

role.admin=ADMIN
role.user=USER

# CORS Configuration
spring.security.cors.configurationSource.allowedOrigins=http://localhost:3000
spring.security.cors.configurationSource.allowedMethods=*
spring.security.cors.configurationSource.allowedHeaders=*
spring.security.cors.configurationSource.allowCredentials=true
spring.security.cors.configurationSource.exposedHeaders=Authorization
spring.security.cors.configurationSource.maxAge=3600